# Site settings
title: "Boris J.Hager"
description: "A resume of my career life."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Boris J.Hager"
resume_title:                   "VP of Global Communications"

resume_header_intro: "<p>sdfdsfdsfds</p>"

# Decide which sections to use
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true

# Design settings
resume_theme:                   default
