# Site settings
title: "Boris J.Hager"
description: "A resume of my career life."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Boris J.Hager"
resume_title:                   "Short version"

resume_header_intro: "<p>With more than 15 years of IT experience, from software development to the management and leadership of various teams and departments, I offer not only specialist expertise but also entrepreneurial experience. Below you can find out about my most important stations, projects and some skills.</p>"

# Decide which sections to use
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true

# Design settings
resume_theme:                   default
